name: colibri
version: '0.1.0'
profile: colibri
vars:
  timezone: 'America/Sao_Paulo'
  bucket_lake: 'colibri-dev'

model-paths: ["modelos"]

models:
  colibri:
    staging:
      +materialized: table
      +schema: staging
    intermediate:
      +database: lake
      +materialized: view
      +schema: intermediate
    marts:
      +database: lake
      +materialized: view
      +schema: marts