[build-system]
requires = ["setuptools>=64"]
build-backend = "setuptools.build_meta"

[project]
name = "colibri"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "boto3",
    "click",
    "databricks-sql-connector",
    "dbt-duckdb==1.10.1",
    "duckdb==1.4.5",
    "numpy",
    "pandas",
    "pyarrow",
    "PyYAML",
    "requests",
    "pipe",
    "rich",
    "tqdm",
]

[project.scripts]
colibri = "cli:cli"

[tool.setuptools]
py-modules = ["cli"]

[tool.setuptools.packages.find]
where = ["."]
